/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Parcel } from "./Parcel";
export * as factories from "./factories";
export { Parcel__factory } from "./factories/Parcel__factory";
